### ISSUE TITLE
为什么没有评论功能...

### ISSUE THREAD

**Issue by bewils** [zjzsliyang/zjzsliyang.github.io#1]
多说现在挂了可以试试 DISQUS(要翻墙
或者可以试试 https://github.com/search?utf8=%E2%9C%93&q=comment+issue&type=
gitalk 和 gitment 看起来都还不错(你可以踩踩坑2333

顺便...functional swift 我还没看 给大佬跪了 Orz

**Comment by zjzsliyang** [comment]
可以可以 又学到了
最近一直在看这种东西😂太菜了

**Comment by bewils** [comment]
本来想在原文底下膜拜 dalao
非要开个 issue 来膜拜嘛
(￣.￣)

**Comment by zjzsliyang** [comment]
在下发现除了 每次写完都要去页面初始化一下以外。。。
还是挺好用的。😂
